### ISSUE TITLE
Add bootstrap folder to project

### ISSUE THREAD

**Issue by bonbons0220** [idies/sciserver-sso-portal#5]
Currently bootstrap build the css and js into a dist folder in bootstrap. I was just moving the css file over manually when I rebuilt it, but if the bootstrap folder is included I will just add the css and js files to the VS project in their current location.

Ignore node_modules in gitignore. path names are too long anyhow.

**Comment by raddick** [comment]
Is this done?

**Comment by raddick** [comment]
Appears to be done - there is a "bootstrap" folder in the project.
