### ISSUE TITLE
Why do we show the token ID as part of registration confirmation?

### ISSUE THREAD

**Issue by raddick** [idies/sciserver-sso-portal#8]
When a new user is created, the confirmation screen shows the username and the token ID. See attached screenshot.

Why do we show the token ID for confirmation? Are there situations where the user will need to know this? If there is, that's fine, we should show it. If not, it's just extra information that will confuse the user.

This is just a question now; assigning to Mitya to ask.

**Comment by dmedv** [comment]
Because we might need to enter it to access other services, like in the Python code you need a token to access CasJobs through the SciServer library.
