### ISSUE TITLE
Change error message for username already taken

### ISSUE THREAD

**Issue by raddick** [idies/sciserver-sso-portal#9]
When a user tries to register using a username that is already taken, here is the error message that is shown:

`Response status code does not indicate success: 409 (Conflict).`

The code functions correctly, and the error message does correctly indicate what the problem is, but the message could be a bit more user-focused.

Self-assigning to write a new one.

**Comment by dmedv** [comment]
I can change the message, but see #10

**Comment by dmedv** [comment]
Changed to "Username already exists." 
Let me know if you want something else.
Marking as closed.
